### ekf config file ###
ekf_filter_node:
    ros__parameters:

        frequency: 30.0
        two_d_mode: true
        # publish_acceleration: true
        publish_tf: true

        map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" if unspecified
        world_frame: odom           # Defaults to the value of odom_frame if unspecified

        odom0: /diff_cont/odom

        odom0_config: [false, false, false,
                       false, false, true,
                       true, true, false,
                       false, false, true,
                       false, false, false]

        odom0_differential: false

        imu0: /bno055/imu
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      true, false, false]

        imu0_differential: false
		imu0_relative: true
